### ISSUE TITLE
Py3 compat: sock.recv() returns bytes, not str - TypeError in connect() in managesieve.py

### ISSUE THREAD

**Issue by cooox** [tonioo/sievelib#47]
I have looked into your mentions of Python3 compatibility, and created a virtualenv with Python 3.6.
As soon as STARTTLS is initialized, the following exception appears when reading from the socket:

```python
  File "~/.virtualenvs/sievelib/lib/python3.6/site-packages/sievelib/managesieve.py", line 489, in connect
    if not self.__get_capabilities():
  File "~/.virtualenvs/sievelib/lib/python3.6/site-packages/sievelib/managesieve.py", line 267, in __get_capabilities
    code, data, capabilities = self.__read_response()
  File "~/.virtualenvs/sievelib/lib/python3.6/site-packages/sievelib/managesieve.py", line 198, in __read_response
    line = self.__read_line()
  File "~/.virtualenvs/sievelib/lib/python3.6/site-packages/sievelib/managesieve.py", line 162, in __read_line
    self.__read_buffer += nval
TypeError: must be str, not bytes
```
This error appears, because Python 3 returns Bytes in [socket.recv()](https://docs.python.org/3.6/library/socket.html#socket.socket.recv), not str as in 2.7. A concatenation with the initialized `self.__read_buffer = ""` (str) does not work.

It's easy to reproduce:
```python
>>> a = "abc"
>>> b = 'def'.encode('utf8')
>>> a += b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: must be str, not bytes
>>> type(a), type(b)
(<class 'str'>, <class 'bytes'>)
>>> a += b.decode('utf8')
>>> a
'abcdef'
```

This can be fixed with `self.__read_buffer += nval.decode('utf8')` in managesieve.py line 162, but the TypeError then appears at another place. So I guess it's a general socket handling compatibility problem.

**Comment by tonioo** [comment]
@cooox I think this issue is already fixed by #46

**Comment by cooox** [comment]
@tonioo I tested your branch, but it did not solve the problem.
I created a PR with a fix that works with Python 2.7 and 3.6, using combinations of

- Client.listscripts()
- Client.capability()
- PLAIN
- LOGIN
